# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakao_user',
            name='recent_search',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kakao_user',
            name='search_number',
            field=models.IntegerField(default=0),
        ),
    ]
