# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161030_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='recent_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=20, unique=True, verbose_name='학수번호')),
                ('lecture_name', models.CharField(max_length=30, verbose_name='강의 이름')),
                ('professor_name', models.CharField(max_length=30, verbose_name='교수 이름')),
            ],
        ),
        migrations.RemoveField(
            model_name='kakao_user',
            name='recent_search',
        ),
        migrations.AddField(
            model_name='recent_search',
            name='kakao_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kakao_user'),
        ),
    ]
