# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161030_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='major_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=25, unique=True, verbose_name='전공')),
                ('recent_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
