# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_major_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.major_list'),
        ),
        migrations.AlterField(
            model_name='recent_search',
            name='course_number',
            field=models.CharField(max_length=20, verbose_name='학수번호'),
        ),
    ]
