# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161103_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_search',
            name='course_number',
        ),
        migrations.RemoveField(
            model_name='recent_search',
            name='lecture_name',
        ),
        migrations.RemoveField(
            model_name='recent_search',
            name='professor_name',
        ),
        migrations.AddField(
            model_name='recent_search',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lecture'),
        ),
    ]
