# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161103_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='major_list',
            name='major_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='major_list',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='major_list',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='major_list',
            name='major_name',
            field=models.CharField(max_length=25, verbose_name='전공'),
        ),
    ]
