# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161107_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='major_list',
            name='category',
            field=models.IntegerField(null=True),
        ),
    ]
