# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161107_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='course_date',
            field=models.CharField(max_length=30, null=True, verbose_name='강의일'),
        ),
    ]
