# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_lecture_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='major_list',
            name='recent_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
