# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20161107_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='major_list',
            name='on_off',
            field=models.BooleanField(default=True),
        ),
    ]
